name = "Create: Lone Block"
author = "RapidFuge"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "944be05f525edeb7de093e09bd143eb41f7106f440761325a4879087c8b6886a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
